#!/usr/bin/env bash
# Stage README.md and LICENSE into the main npm package directory and every
# per-platform package directory generated by `napi create-npm-dirs`. Must be
# run from the repository root.
set -euo pipefail

assets=("README.md" "LICENSE")

for asset in "${assets[@]}"; do
  test -f "$asset" || { echo "ERROR: $asset not found at repository root" >&2; exit 1; }
  cp "$asset" "npm/$asset"
  for package_dir in npm/npm/*/; do
    cp "$asset" "${package_dir}${asset}"
  done
done
